import type { ReactNode } from "react";
import { Link } from "../router";

export const REPO_URL = "https://github.com/variable25/Automated-RAG-and-LLM-decision-pipelines";
const ISSUES_URL = `${REPO_URL}/issues`;
const UPDATED = "7 October 2026";

function LegalPage({ title, intro, children }: { title: string; intro: string; children: ReactNode }) {
  return (
    <article className="legal">
      <p className="eyebrow">Last updated {UPDATED}</p>
      <h1>{title}</h1>
      <p className="lead">{intro}</p>
      {children}
      <p className="muted small">
        Questions? Open an issue on <a href={ISSUES_URL}>GitHub</a>. See also the{" "}
        {title === "Privacy policy" ? <Link href="/terms">terms of use</Link> : <Link href="/privacy">privacy policy</Link>}.
      </p>
    </article>
  );
}

export function Privacy() {
  return (
    <LegalPage
      title="Privacy policy"
      intro="RAG Decision Explorer is a read-only research demo. It has no accounts, no forms, no cookies and no analytics, so it collects as little about you as a website can."
    >
      <h2>Who runs this site</h2>
      <p>
        This site is a personal, non-commercial project published by the GitHub user{" "}
        <a href="https://github.com/variable25">variable25</a>. The simplest way to reach us is an issue on the{" "}
        <a href={ISSUES_URL}>project repository</a>.
      </p>

      <h2>What we collect</h2>
      <ul>
        <li>
          <strong>No cookies, no local storage, no tracking.</strong> The site stores nothing in your browser and uses
          no analytics, advertising or social media scripts.
        </li>
        <li>
          <strong>No personal data you enter.</strong> There are no sign-ups or forms. Search and filter choices on the
          Questions page stay in your browser and are never sent to us.
        </li>
        <li>
          <strong>Standard server logs.</strong> The site runs on Google Cloud Run in the europe-west1 (Belgium) region.
          Like any web server, it records each request automatically: your IP address, the time, the page or data
          requested, your browser's user agent and the response status. These logs are used only to keep the service
          running and secure, and are deleted automatically after Google Cloud Logging's default retention of 30 days.
        </li>
      </ul>

      <h2>Third parties</h2>
      <p>
        Fonts, scripts and data are all served from this site itself; your browser does not contact any other service
        while you use it. Google Cloud processes the server logs above on our behalf. Links to GitHub, Hugging Face or
        Wikipedia take you to sites with their own privacy policies.
      </p>

      <h2>Legal basis and your rights</h2>
      <p>
        We process server logs on the basis of our legitimate interest in operating and securing the site (Art. 6(1)(f)
        GDPR). You may ask for access to, or deletion of, data about you, or object to its processing, by opening an
        issue (please don't post personal details publicly; ask for a private contact instead). Because the logs hold
        no names or accounts, we can only find entries if you tell us the IP address and time of your visit. You also
        have the right to complain to your data protection authority.
      </p>

      <h2>Changes</h2>
      <p>If this policy changes, the new version will be posted here with a new date.</p>
    </LegalPage>
  );
}

export function Terms() {
  return (
    <LegalPage
      title="Terms of use"
      intro="By using this site you agree to these terms. They are short because the site is simple: it shows the results of an experiment and nothing more."
    >
      <h2>What this site is</h2>
      <p>
        A free, read-only dashboard of an experiment that measures when a language model should look up Wikipedia
        before answering. It is provided for research and education.
      </p>

      <h2>The answers are often wrong, on purpose</h2>
      <p>
        Every answer shown was generated by an AI model, and many are incorrect: measuring those mistakes is the point
        of the experiment. Do not rely on anything here as a fact or use it for decisions about people, health, money
        or law.
      </p>

      <h2>Acceptable use</h2>
      <p>
        Please don't try to disrupt or overload the service, probe it for vulnerabilities, or scrape it at high
        volume. The complete data is already published in the <a href={REPO_URL}>repository</a>.
      </p>

      <h2>Third-party content</h2>
      <ul>
        <li>
          Questions and accepted answers come from the{" "}
          <a href="https://huggingface.co/datasets/akariasai/PopQA">PopQA dataset</a> (Mallen et al., 2023).
        </li>
        <li>Model answers were generated with Meta Llama 3 8B Instruct. Built with Meta Llama 3.</li>
        <li>
          Retrieved context came from <a href="https://en.wikipedia.org/">Wikipedia</a> articles, available under
          CC BY-SA 4.0.
        </li>
      </ul>
      <p>Each of these remains under its own license and terms.</p>

      <h2>No warranty</h2>
      <p>
        The site and its content are provided "as is", without warranties of any kind. To the extent permitted by law,
        we are not liable for any loss arising from using the site or relying on its content. The service may change or
        go offline at any time.
      </p>

      <h2>Changes</h2>
      <p>We may update these terms; the current version and its date are always on this page.</p>
    </LegalPage>
  );
}
